#!/usr/bin/env python3
"""Negative rule engine: Executes expressions generated by a large model on the input."""
import re
from typing import Dict, Any, List
import builtins

# Allowed security built-in
SAFE_BUILTINS = {
    "isinstance", "len", "dict", "list", "str", "int", "bool", "any", "all", "range"
}

clean_globals = {
    "__builtins__": {k: getattr(builtins, k) for k in SAFE_BUILTINS},
    "re": re
}

def eval_rule(param_value: Any, rules: List[Dict[str, Any]], whole_obj: Dict[str, Any]) -> bool:
    result = None
    for rule in rules:
        expr = rule["expression"]
        try:
            result = bool(eval(expr, clean_globals, whole_obj.get("params")))
        except Exception as e:
            print('Error infos', e)
    if not result:
        return False
    return True